<h2>Atribuir Perfil ao Usuário</h2>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <p>Usuário: <b><?php echo $this->usuario->usr_nome; ?></b></p>

        <h5>Atribuir novo perfil</h5>

        <div class="hero">
            <input type="hidden" id="usuarioId" value="<?php echo $this->usuario->usrId; ?>">

            <select name="modulo" id="modulo">
                <option>Escolha o módulo</option>
                <?php foreach ($this->modulos as $key => $value) : ?>
                        <option value='<?php echo $value->id; ?>'><?php echo $value->descricao; ?></option>
                <?php endforeach; ?>
            </select>

            <select name="perfis" id="perfis" style="display:none;"></select>

            <a class="btn btn-small btn-info" href="#" id="btnSalvar" style="margin-bottom: 11px; display:none;"><i class="icon-plus-sign icon-white"></i> Adicionar Perfil</a>

        </div>

        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Módulo</th>
                    <th>Perfil</th>
                    <th>Descrição do perfil</th>
                    <th style="width:27px;">Excluir</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->usuarioPerfis as $key => $value) : ?>
                    <tr>
                        <td><?php echo $value->prfId; ?></td>
                        <td><?php echo $value->modNome; ?></td>
                        <td><?php echo $value->prfNome; ?></td>
                        <td><?php echo $value->prfDescricao; ?></td>
                        <td class="text-center">
                            <a class='btn btn-danger btn-xs' href='#'
                                        data-perfilid='<?php echo $value->prfId; ?>'
                                        data-usuarioid='<?php echo $this->usuario->usrId; ?>'>
                                <i class='glyphicon glyphicon-trash'></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    $(".btn-danger").click(function(e){
        var perfilid  = $(e.currentTarget).data('perfilid');
        var usuarioid = $(e.currentTarget).data('usuarioid');
        bootbox.confirm("Você tem certeza que deseja desvincular esse perfil do usuário?", function(result) {
            if (result)
            {
                ids = [usuarioid, perfilid];
                deleteById('perfisusuarios', ids);
            }
        });
    });

    $("#modulo").change(function(e){
        var perfis  = $("#perfis");
        var id      = $("#modulo").val();

        popularSelectByIdInGerenciaPerfis( id, $("#perfis"), 'getperfisbymoduloid', $("#btnSalvar") );
    });

    $("#btnSalvar").click(function(){
        var estilo = $("#perfis").css('display');
        var usuarioid = parseInt($("#usuarioId").val());
        var perfilid = parseInt($("#perfis").val());

        if (estilo != 'none' && usuarioid > 0 && perfilid > 0) {
            window.location.href = '/admin/perfisusuarios/atribuirperfilusuario/' + usuarioid + '/' + perfilid;
        }
    });

</script>
