<h2>Perfis ao Usuários</h2>
<div class="row">
    <?php
        if (sizeof($this->menuButtons))
            $this->menuBar($this->menuButtons);
    ?>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Usuário</th>
                    <th style="width:98px; text-align: center;">Ação</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->usuarios as $key => $value) : ?>
                    <tr>
                        <td><?php echo $value->usrId; ?></td>
                        <td><?php echo $value->usrNome; ?></td>
                        <td>
                            <a class='btn btn-success' href='#' data-id="<?php echo $value->usrId; ?>">
                                <i class='glyphicon glyphicon-ok'></i> Atribuir perfil
                            </a>
                        </td>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $('.btn-success').click(function(e) {
        var itemSelecionado = $(e.currentTarget).data('id');
        ids = [itemSelecionado];
        goToAction('perfisusuarios','gerenciarperfisusuario',ids);
    });
</script>
