<h2>Atualizar um comentário</h2>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<?php
			echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formHidden($form->get('commentDate'));
            echo $this->elementToRow($form->get('postsId'));
            echo $this->elementToRow($form->get('description'));
            echo $this->elementToRow($form->get('name'));
            echo $this->elementToRow($form->get('email'));
            echo $this->elementToRow($form->get('webpage'));
            echo $this->elementToSubmit($form->get('submit'));
        	echo $this->form()->closeTag();
        ?>
	</div>
</div>

<script>
    $(function() {
        var dt = new Date();
        var dtstring = dt.getFullYear()
            + '-' + (dt.getMonth()+1)
            + '-' + dt.getDate()
            + ' ' + dt.getHours()
            + ':' + dt.getMinutes()
            + ':' + dt.getSeconds();
        $('input[name="commentDate"]').val(dtstring);
    });

    var id = $('select[name="postsId"]').data('id');
    setSelected($('select[name="postsId"] option'), id);
</script>
