<?php echo $this->doctype(); ?>

<html lang="pt_BR">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headTitle('Blog NTI - Administração')->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/uema_logo.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

       <!-- Scripts -->
        <?php
            echo $this->inlineScript()
                    ->prependFile($this->basePath('/js/bootbox.min.js'))
                    ->prependFile($this->basePath('js/bootstrap.min.js'))
                    ->prependFile($this->basePath('js/jquery.min.js'))
                    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                    ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
                    ->prependFile($this->basePath('js/utils/routes.js'))
                    ->prependFile($this->basePath('js/utils/utils.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo "Módulo de Administração"; ?></a>
                </div>
                <div class="nav-collapse">
                  <ul class="nav navbar-nav nav-stacked navbar-right">
                      <li>
                        <a data-toggle="dropdown" href="#" class="dropdown-toggle user-menu">
                            <span id="user_info">
                                <small>Bem Vindo,</small> <?php echo $this->session()->offsetGet('zf2base_loggeduser')->usr_nome; ?>
                            </span>
                            <b class="caret"></b>
                            <ul id="user_menu" class="pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer">
                                <li><a href="#"><i class="icon-cog"></i> Configurações</a></li>
                                <li><a href="/application/perfil"><i class="icon-user"></i> Perfil</a></li>
                                <li class="divider"></li>
                                <li><a href="/application/auth/logout"><i class="icon-off"></i> Sair</a></li>
                            </ul>
                        </a>
                      </li>
                  </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
              <div class="col-sm-3 col-md-2 sidebar">
                  <div class="panel-group" id="accordion">
                      <?php echo $this->navigation('navigation')->menu()->setPartial(array('admin/partials/menu', 'Admin'))->render(); ?>
                  </div>
                  <div id="sidebar-collapse">
                      <i class="icon-double-angle-left"></i>
                  </div>
              </div>
              <div class="col-sm-9 main">
                      <?php
                          echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial(array('admin/partials/breadcrumbs', 'Admin'));
                      ?>
                      <?php
                          $message = empty($this->flashMessage()) ? NULL : $this->flashMessage();
                          echo strlen($message) > 0 ? $message : '';
                      ?>
                      <?php echo $this->content; ?>
              </div>
            </div>
        </div>
        <div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
            <div class="container">
                  <div class="navbar-text pull-left">
                      <footer>
                        Todos os direitos reservados Universidade Estadual do Maranhão - UEMA.<BR>
                        Cidade Universitária Paulo VI – Caixa Postal 09 – São Luís/MA. FONE: (98) 3245–5461 FAX: (98) 3245–5882.<BR>
                        Pró-Reitoria de Planejamento - PROPLAN. FONE: (98) 3245-2833 <BR>
                        Núcleo de Tecnologias da Informação - NTI. FONE: (98) 3245-2400
                        <p>&copy; <?php echo date('Y') ?> by NTI. <?php echo $this->translate('All rights reserved.') ?></p>
                      </footer>
                  </div>
            </div>
        </div>
    </body>

</html>
