<h2>Atribuir permissões ao Perfil</h2>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <p>Perfil: <b><?php echo $this->perfil->prf_nome; ?></b>  | Módulo: <b><?php echo $this->perfil->mod_nome; ?></b></p>

    <form method="POST" action="/admin/perfispermissoes/salvarpermissoesperfil">
        <input type="hidden" name="prf_id" value="<?php echo $this->perfil->prf_id; ?>">
        <input type="hidden" name="mod_id" value="<?php echo $this->perfil->mod_id; ?>">
        <div class="accordion" id="accordion2">
            <?php foreach ($this->permissoes as $key => $value) : ?>
                <div class='accordion-group'>
                    <div class='accordion-heading'>
                        <a class='accordion-toggle' data-toggle='collapse' data-parent='#accordion2' href='#collapse<?php echo $value['rcs_id']; ?>'>
                                # <?php echo $value['rcs_id']?> - <?php echo $value['rcs_nome'] ?>
                        </a>
                    </div>
                    <div id='collapse<?php echo $value['rcs_id']; ?>' class='accordion-body collapse'>
                        <div class='accordion-inner'>
                            <?php foreach ($value['permissoes'] as $k => $v) : ?>
                                <?php $checked = $v['habilitado'] != 0 ? "checked='checked'" : ''; ?>
                                <label>
                                    <input name='permissoes[]' <?php echo $checked; ?> type='checkbox' value='<?php echo $v['prm_id']; ?>'/>
                                    <span class='lbl'> <?php echo $v['prm_nome']; ?></span>
                                </label>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <?php if (sizeof($this->permissoes)) : ?>
            <input type='submit' name='submit' class='btn btn-primary' value='Salvar'>
        <?php endif; ?>
    </form>
</div>
</br>
</br>
</br>
