<h2>Comentários</h2>
<div class="span12 alert alert-normal">
    <a class="btn btn-small btn-success" href="/blogparte1/comments/create">
        <i class="glyphicon glyphicon-plus"></i> 
        Novo
    </a>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Post</th>
                    <th>Comentário</th>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Web-page</th>
                    <th>Última atualização</th>
                    <th style="width:27px;">Editar</th>
                    <th style="width:27px;">Excluir</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($comments as $key => $value) : ?>
                <tr>
                    <td><?php echo $value->getId(); ?></td>
                    <td><?php echo $value->getPostsId()->title; ?></td>
                    <td><?php echo $value->getDescription(); ?></td>
                    <td><?php echo $value->getName(); ?></td>
                    <td><?php echo $value->getEmail(); ?></td>
                    <td><?php echo $value->getWebpage(); ?></td>
                    <td><?php echo $value->getCommentDate(); ?></td>
                    <td class="text-center">
                        <a class='btn btn-warning btn-xs' href='/blogparte1/comments/update/<?php echo $value->getId(); ?>'>
                            <i class='glyphicon glyphicon-pencil'></i>
                        </a>
                    </td>
                    <td class="text-center">
                        <a class='btn btn-danger btn-xs' href='/blogparte1/comments/delete/<?php echo $value->getId(); ?>'>
                            <i class='glyphicon glyphicon-trash'></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    /*$(".btn-danger").click(function(e){
        
        var itemSelecionado = $(e.currentTarget).data('id');
        bootbox.confirm("Você tem certeza que deseja excluir esse post?", function(result) {
            if (result)
            {
                ids = [itemSelecionado];
                deleteById( 'comments', ids );
            }
        });
    });

    $(".btn-warning").click(function(e){
        
        var itemSelecionado = $(e.currentTarget).data('id');
        ids = [itemSelecionado];
        updateById('comments', ids );
    });*/

</script>