<h2>Usuários</h2>
<div class="row">
    <?php
        if (sizeof($this->menuButtons))
            $this->menuBar($this->menuButtons);
    ?>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome completo</th>
                    <th>Email</th>
                    <th style="width:27px;">Editar</th>
                    <th style="width:27px;">Excluir</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($usuarios as $key => $value) : ?>
                    <tr>
                        <td><?php echo $value->usrId;?></td>
                        <td><?php echo $value->usrNome;?></td>
                        <td><?php echo $value->usrEmail;?></td>
                        <td class="text-center">
                            <a class="btn btn-xs btn-warning" href="/admin/usuarios/update/<?php echo $value->usrId;?>" data-id="<?php echo $value->usrId;?>">
                                <i class="glyphicon glyphicon-pencil"></i>
                            </a>
                        </td>
                        <td  class="text-center">
                            <a class="btn btn-xs btn-danger" href="#" data-id="<?php echo $value->usrId;?>">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    $(".btn-danger").click(function(e){

        var itemSelecionado = $(e.currentTarget).data('id');
        bootbox.confirm("Você tem certeza que deseja excluir esse usuário?", function(result) {
            if (result)
            {
                ids = [itemSelecionado];
                deleteById('usuarios',ids);
            }
        });
    });

    $(".btn-warning").click( function(e) {
        var itemSelecionado = $(e.currentTarget).data('id');
        ids = [itemSelecionado];
        updateById('usuarios',ids);
    });

</script>
