<h2>Atualizar Usuário</h2>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('usrId'));
            echo $this->elementToRow($form->get('usrNome'));
            echo $this->elementToRow($form->get('usrEmail'));
            echo $this->elementToRow($form->get('usrTelefone'));
            echo $this->elementToRow($form->get('usrUsuario'));
            echo $this->checkBoxToRow($form->get('usrAtivo'));
            echo $this->elementToSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div>
</div>

<script type="text/javascript" src="/js/jquery.maskedinput.min.js"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $('#usrTelefone').mask('(99) 99999-9999');

    $("#novousuario").submit(function(){
      $('#usrTelefone').val($('#usrTelefone').mask());
    });
  });
</script>
