<h2>Novo Módulo</h2>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('mod_id'));
            echo $this->elementToRow($form->get('mod_nome'));
            echo $this->elementToRow($form->get('mod_descricao'));
            echo $this->elementToRow($form->get('mod_icone'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div>
</div>
