<ul class="breadcrumb">
    <?php
        // iterate through the pages
        foreach ($this->pages as $key => $page) {
            echo "<li>";
            if ($key == 0) {
                echo "<a class='icon-home'></a> ";
            }
            if ($key < count($this->pages) - 1) {

                echo $page->getLabel();
                //echo $page->getHref();
                /*echo "<span class='divider'><i class='icon-angle-right'></i></span>";*/
            } else {
                echo $page->getLabel();
            }
            echo "</li>";
        }
    ?>
</ul>
