<div class="panel-group" id="accordion">
    <?php foreach ($this->container as $page): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                 <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#<?php echo $page->getLabel(); ?>" aria-expanded="<?php echo ($page->activeMenu ? 'true' : 'false'); ?>" class="<?php echo ($page->activeMenu ? '' : 'collapsed');?>"><span></span><?php echo $page->getLabel(); ?></a>
                </h4>
            </div>
            <?php if(!empty($page->pages)): ?>
                <div id="<?php echo $page->getLabel(); ?>" <?php echo ($page->activeMenu ? 'class="panel-collapse in"' : 'class="panel-collapse collapse"'); ?>>
                    <ul class="list-group">
                        <?php foreach ($page->pages as $subpage): ?>
                            <li <?php echo ($subpage->active ? 'class="list-group-item active"' : 'class="list-group-item"'); ?>>
                                <a href="<?php echo $subpage->getHref(); ?>">
                                    <?php echo $subpage->getLabel(); ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            </li>
        </div>
    <?php endforeach; ?>
</div>
