<div class="row">
  <div class="col-sm-6 col-md-4 col-md-offset-4">
      <h1 class="text-center login-title"><i class="glyphicon glyphicon-log-in blue"></i> Acessar sistema</h1>
      <div class="account-wall">
          <form class="form-signin" method="post" action="/admin/auth/login">
          <input type="text" name="username" class="form-control" placeholder="Usuário" required autofocus>
          <input type="password" name="password" class="form-control" placeholder="Senha" required>
          <button class="btn btn-lg btn-primary btn-block" type="submit">
              Entrar</button>
          <label class="checkbox pull-left">
              <input type="checkbox" value="remember-me">
              Lembre-me
          </label>
          <a href="#" class="pull-right need-help">Precisa de ajuda? </a><span class="clearfix"></span>
          </form>
      </div>
  </div>
</div>
