<h2>Posts</h2>
<hr>

<div class="span12 alert alert-normal">
  <a class="btn btn-small btn btn-success" href="/admin/users/save">
    <i class="glyphicon glyphicon-plus-sign"></i> Novo
  </a>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <table class="table table-hover table-condensed">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome</th>
                <th>Perfil</th>
                <th style="width:27px;">Editar</th>
                <th style="width:27px;">Excluir</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $key => $value) : ?>
            <tr>
                <td><?php echo $value['usr_id']; ?></td>
                <td><?php echo $value['name']; ?></td>
                <td><?php echo $value['role']; ?></td>
                <td class="text-center">
                    <a class="btn btn-warning btn-xs" href="/admin/users/save/<?php echo $value['usr_id']; ?>">
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>
                </td>
                <td class="text-center">
                    <a class="btn btn-danger btn-xs" href="/admin/users/delete/<?php echo $value['usr_id']; ?>">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
