<h2>Novo post</h2>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<?php
			echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('usr_id'));
            echo "<div class='form-group'>";
                echo $this->formInput($form->get('name'));
            echo "</div>";
            echo "<div class='form-group'>";
                echo $this->formInput($form->get('username'));
            echo "</div>";
            echo "<div class='form-group'>";
                echo $this->formInput($form->get('password'));
            echo "</div>";
            echo "<div class='form-group'>";
                echo $this->formSelect($form->get('role'));
            echo "</div>";
            echo "<div class='form-group'>";
                echo $this->formCheckbox($form->get('valid'));
            echo "</div>";
            echo $this->formSubmit($form->get('submit'));
        	echo $this->form()->closeTag();
        ?>
	</div>
</div>
