<h2>Recursos</h2>
<div class="row">
    <?php
        if (sizeof($this->menuButtons))
            $this->menuBar($this->menuButtons);
    ?>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-hover table-condensed data-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Módulo</th>
                    <th>Categoria</th>
                    <th>Recurso</th>
                    <th>Descrição</th>
                    <th style="width:80px;">Ordem</th>
                    <th style="width:27px;">Editar</th>
                    <th style="width:27px;">Excluir</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->recursos as $key => $value) : ?>
                    <tr>
                        <td><?php echo $value->rcs_id ?></td>
                        <td><?php echo $value->mod_nome ?></td>
                        <td><?php echo $value->ctr_nome ?></td>
                        <td><?php echo $value->rcs_nome ?></td>
                        <td><?php echo $value->rcs_descricao ?></td>
                        <td><?php echo $value->rcs_ordem ?></td>
                        <td class="text-center">
                            <a class='btn btn-warning btn-xs' href='#' data-id='<?php echo $value->rcs_id; ?>'>
                                <i class='glyphicon glyphicon-pencil'></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a class='btn btn-danger btn-xs' href='#' data-id='<?php echo $value->rcs_id;?>'>
                                <i class='glyphicon glyphicon-trash'></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('.data-table').DataTable();
    } );
    $(".btn-danger").click(function(e){

        var itemSelecionado = $(e.currentTarget).data('id');
        bootbox.confirm("Você tem certeza que deseja excluir esse recurso?", function(result) {
            if (result)
            {
                ids = [itemSelecionado];
                deleteById('recursos',ids);
            }
        });
    });

    $(".btn-warning").click(function(e){

        var itemSelecionado = $(e.currentTarget).data('id');
        ids = [itemSelecionado];
        updateById('recursos',ids);
    });
</script>
