<h2>Atualizar Recurso</h2>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('rcs_id'));
            echo $this->elementToRow($form->get('rcs_mod_id'));
            echo $this->elementToRow($form->get('rcs_ctr_id'));
            echo $this->elementToRow($form->get('rcs_nome'));
            echo $this->elementToRow($form->get('rcs_descricao'));
            echo $this->elementToRow($form->get('rcs_icone'));
            echo $this->elementToRow($form->get('rcs_ordem'));
            echo $this->checkBoxToRow($form->get('rcs_ativo'));
            echo $this->elementToSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div>
    <input id="categoriaId" type="hidden" data-id="<?php echo $this->categoriaId; ?>" />
    <input id="moduloId" type="hidden" data-id="<?php echo $this->moduloId; ?>" />
</div>

<script type="text/javascript">
    var categoriaId = $('#categoriaId').data('id');
    var moduloId    = $('#moduloId').data('id');
    setSelected($('select[name="rcs_ctr_id"] option'), categoriaId);
    setSelected($('select[name="rcs_mod_id"] option'), moduloId);
</script>
