<h2>Posts</h2>
<hr>

<div class="span12 alert alert-normal">
  <a class="btn btn-small btn btn-success" href="/blogparte1/posts/create">
    <i class="glyphicon glyphicon-plus-sign"></i> Novo
  </a>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <table class="table table-hover table-condensed">
        <thead>
            <tr>
                <th>#</th>
                <th>Título</th>
                <th>Conteúdo</th>
                <th>Última atualização</th>
                <th style="width:27px;">Editar</th>
                <th style="width:27px;">Excluir</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($posts as $key => $value) : ?>
            <tr>
                <td><a href="#" class="go-to-comments" data-id="<?php echo $value->getId();?>"><?php echo $value->getId();?></a></td>
                <td><?php echo $value->getTitle(); ?></td>
                <td><?php echo $value->getDescription(); ?></td>
                <td><?php echo $value->getPostDate(); ?></td>
                <td class="text-center">
                    <a class="btn btn-warning btn-xs" href="/blogparte1/posts/update/<?php echo $value->getId(); ?>">
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>
                </td>
                <td class="text-center">
                    <a class="btn btn-danger btn-xs" href="/blogparte1/posts/delete/<?php echo $value->getId(); ?>">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">

    $(".go-to-comments").click(function(e) {
        var itemSelecionado = $(e.currentTarget).data('id');
        var id = [itemSelecionado];
        var url = '/admin/comments/index/'+id;
        window.location.href = url;
    });

</script>
