<h2>Nova Categoria de Recurso</h2>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('ctr_id'));
            echo $this->elementToRow($form->get('ctr_nome'));
            echo $this->elementToRow($form->get('ctr_descricao'));
            echo $this->elementToRow($form->get('ctr_icone'));
            echo $this->elementToRow($form->get('ctr_ordem'));
            echo $this->checkBoxToRow($form->get('ctr_visivel'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div>
</div>
