<h2>Categorias de Recursos</h2>
<div class="row">
    <?php
        if (sizeof($this->menuButtons))
            $this->menuBar($this->menuButtons);
    ?>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Categoria</th>
                    <th>Descrição</th>
                    <th style="width:80px;">Ordem</th>
                    <th style="width:80px;">Ativo</th>
                    <th style="width:27px;">Editar</th>
                    <th style="width:27px;">Excluir</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->categoriasRecursos as $key => $value) : ?>
                    <tr>
                        <td><?php echo $value->ctr_id; ?></td>
                        <td><?php echo $value->ctr_nome; ?></td>
                        <td><?php echo $value->ctr_descricao; ?></td>
                        <td><?php echo $value->ctr_ordem; ?></td>
                        <td><?php echo $value->ctr_visivel; ?></td>
                        <td class="text-center">
                            <a class='btn btn-warning btn-xs' href='#' data-id='<?php echo $value->ctr_id; ?>'>
                                <i class='glyphicon glyphicon-pencil'></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a class='btn btn-danger btn-xs' href='#' data-id='<?php echo $value->ctr_id; ?>'>
                                <i class='glyphicon glyphicon-trash'></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    $(".btn-danger").click(function(e){

        var itemSelecionado = $(e.currentTarget).data('id');
        bootbox.confirm("Você tem certeza que deseja excluir essa categoria?", function(result) {
            if (result)
            {
                ids = [itemSelecionado];
                deleteById('categoriasrecursos', ids);
            }
        });
    });

    $(".btn-warning").click(function(e) {
        var itemSelecionado = $(e.currentTarget).data('id');
        ids = [itemSelecionado];
        updateById('categoriasrecursos', ids);
    })

</script>
