<h2>Blog</h2>
<hr>


<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>Título</th>
                    <th>Conteúdo</th>
                    <th>Última atualização</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($posts as $key => $value) : ?>
                <tr>
                    <td><?php echo ($value['title']); ?></td>
                    <td><?php echo ($value['description']); ?></td>
                    <td><?php echo ($value['post_date']); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>