<div class="jumbotron">
    <h1>Bem vindo ao blog do CursoZF2</h1>
    <p><a class="btn btn-primary btn-lg" href="http://framework.zend.com/" target="_blank" role="button">Site oficial do ZF2</a></p>
</div>

<?php foreach ($posts as $key => $value) : ?>
<div class="row">
    <div class="col-sm-6 col-md-12">
        <div class="thumbnail">
            <div class="caption">
                <h3><?php echo ($value['title']); ?></h3>
                <p><?php echo ($value['description']); ?></p>
                <p><?php echo ($value['post_date']); ?></p>
            </div>
        </div>
    </div>
</div>
<?php endforeach; ?>
