<h2>Notícias</h2>
<div class="row">
    <?php
        if (sizeof($this->menuButtons))
            $this->menuBar($this->menuButtons);
    ?>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Data</th>
                    <th>Notícia</th>
                    <th style="width:27px;">Editar</th>
                    <th style="width:27px;">Excluir</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($resultSet as $key => $value) : ?>
                    <tr>
                        <td>$value->ntc_id</td>
                        <td>$value->ntc_data</td>
                        <td>$value->ntc_mensagem</td>
                        <td>
                            <a class='btn btn-warning btnxs' href='#/admin/noticias/update/".$value->ntc_id."' data-id='<?php echo $value->ntc_id; ?>'>
                                <i class='glyphicon glyphicon-pencil'></i>
                            </a>
                        </td>
                        <td>
                            <a class='btn btn-danger btn-xs' href='#' data-id='<?php echo $value->ntc_id; ?>'>
                                <i class='glyphicon glyphicon-trash'></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    $(".btn-danger").click(function(e){

        var itemSelecionado = $(e.currentTarget).data('id');
        bootbox.confirm("Você tem certeza que deseja excluir essa notícia?", function(result) {
            if (result)
            {
                ids = [itemSelecionado];
                deleteById('noticias', ids);
            }
        });
    });

    $(".btn-warning").click(function(e){

        var itemSelecionado = $(e.currentTarget).data('id');
        ids = [itemSelecionado];
        updateById('noticias', ids);
    });

</script>
