<h2>Alterar Notícia</h2>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('ntc_id'));
            echo $this->elementToRow($form->get('ntc_data'));
            echo $this->elementToRow($form->get('ntc_mensagem'));
            echo $this->elementToSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div>
</div>
