<h2>Posts</h2>
<hr>
<div class="row">
    <?php
        if (sizeof($this->menuButtons))
            $this->menuBar($this->menuButtons);
    ?>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Título</th>
                    <th>Conteúdo</th>
                    <th>Última atualização</th>
                    <th style="width:27px;">Editar</th>
                    <th style="width:27px;">Excluir</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($resultSet as $key => $value) : ?>
                <tr>
                    <td><a href='#' class="go-to-comments" data-id="<?php echo $value->id; ?>"><?php echo $value->id; ?></a></td>
                    <td><?php echo $value->title; ?></td>
                    <td><?php echo $value->description; ?></td>
                    <td><?php echo $value->postDate; ?></td>
                    <td class="text-center">
                        <a class='btn btn-warning btn-xs' href='#' data-id="<?php echo $value->id; ?>">
                            <i class='glyphicon glyphicon-pencil'></i>
                        </a>
                    </td>
                    <td class="text-center">
                        <a class='btn btn-danger btn-xs' href='#' data-id="<?php echo $value->id; ?>">
                            <i class='glyphicon glyphicon-trash'></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    $(".btn-danger").click(function(e){

        var itemSelecionado = $(e.currentTarget).data('id');
        bootbox.confirm("Você tem certeza que deseja excluir esse post?", function(result) {
            if (result)
            {
                ids = [itemSelecionado];
                deleteById( 'posts', ids );
            }
        });
    });

    $(".btn-warning").click(function(e){

        var itemSelecionado = $(e.currentTarget).data('id');
        ids = [itemSelecionado];
        updateById('posts', ids );
    });

    $(".go-to-comments").click(function(e) {

        var itemSelecionado = $(e.currentTarget).data('id');
        ids = [itemSelecionado];
        redirectToIndex('comments', ids );
    });

</script>
