<h2>Atualizar post</h2>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<?php
			echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formHidden($form->get('postDate'));
            echo $this->elementToRow($form->get('title'));
            echo $this->elementToRow($form->get('description'));
            echo $this->formSubmit($form->get('submit'));
        	echo $this->form()->closeTag();
        ?>
	</div>
</div>
<script>
    $(function() {
        var dt = new Date();
        var dtstring = dt.getFullYear()
            + '-' + (dt.getMonth()+1)
            + '-' + dt.getDate()
            + ' ' + dt.getHours()
            + ':' + dt.getMinutes()
            + ':' + dt.getSeconds();
        $('input[name="postDate"]').val(dtstring);
    });
</script>
